---
title: "Cyclystic Case Study"
author: "Melvin Chang"
date: ""
output: html_document
---

## Introduction

This is a case study for a fictional bike-share company called Cyclistic as part of the Google Data Analytics Capstone Project.

Cyclistic launched its bike-share program in 2016 which has grown to a fleet of 5,824 bicycles which are geotracked and locked into a network of 692 stations across Chicago. The bikes can be unlocked from one station and returned to any other station in the system at any time.

The company offers single-ride passes, full-day passes, and annual memberships. Customers who purchase single-ride or full-day passes are referred to as casual rider. Customers who purchase annual memberships are Cyclistic members. 

Cyclistic's finance analysts have concluded that annual members are much more profitable than casual riders. The director of marketing believes that the company's future success depends on maximizing the number of annual memberships. Thus, the goal of the director of marketing is to design marketing strategies which aim to convert casual riders into annual members. However, before doing so, the team needs to have a better understanding of **how annual members and casual riders differ**, why casual riders would buy a membership, and how digital media could affect their marketing tactics. They would like to analyze the Cyclystic historical bike trip data to identify trends.

The data that was used for this case study was for the year 2024 which can be found [here](https://divvy-tripdata.s3.amazonaws.com/index.html). 

## Questions

Three questions will guide the future marketing program:

1. How do annual members and casual riders use Cyclistic bikes differently? 
2. Why would casual riders buy Cyclistic annual memberships?
3. How can Cyclystic use digital media to influence casual riders to become members?

For this case study, I am tasked to answer the first question: How do annual members and casual riders use Cyclistic bikes differently?


